/* Genera el diccionario DTC en español a partir de la fuente MIT verificada.
   Chequeo duro: si queda cualquier palabra en inglés sin traducir, falla. */
const fs = require('fs');
const T = __dirname + '/';

const crudos = JSON.parse(fs.readFileSync(T + 'verificados.json', 'utf8'));

/* 1. Normalizar erratas de la fuente (lista comunitaria con artefactos de OCR) */
function normalizar(d) {
  return d
    .replace(/\b02 Sensor\b/gi, 'O2 Sensor')
    .replace(/\bBank I\b/g, 'Bank 1')
    .replace(/\bSensor I\b/g, 'Sensor 1')
    .replace(/\bPetal\b/gi, 'Pedal')
    .replace(/\s+/g, ' ')
    .trim();
}

/* 2. Frases largas primero; el orden importa */
const FRASES = [
  // casos completos que el motor de reglas arma mal
  [/\bTransmission Control System\b/gi, 'Sistema de control de la transmisión'],
  [/\bTorque Converter\/Clutch Solenoid\b/gi, 'Solenoide del convertidor\/embrague'],
  [/\bPerformance or Stuck Off\b/gi, 'desempeño o atascado apagado'],
  [/\bPerformance or Stuck On\b/gi, 'desempeño o atascado encendido'],
  [/\bSingle Sensor\b/gi, 'sensor único'],
  [/\bFlow Insufficient Detected\b/gi, '— flujo insuficiente'],
  [/\bFlow Excessive Detected\b/gi, '— flujo excesivo'],
  [/\bExcessive Flow Detected\b/gi, '— flujo excesivo'],
  [/\bInsufficient Flow Detected\b/gi, '— flujo insuficiente'],
  [/\bSystem Performance\b/gi, 'Sistema — desempeño'],
  [/\bClosed Position Performance\b/gi, 'desempeño en posición cerrada'],
  [/\bOpen Position Performance\b/gi, 'desempeño en posición abierta'],
  [/\bLeak Detected \(small leak\)/gi, 'fuga pequeña detectada'],
  [/\bLeak Detected \(gross leak\)/gi, 'fuga grande detectada'],
  [/\bLeak Detected\b/gi, 'fuga detectada'],
  [/\bCold Start Injector\b/gi, 'Inyector de arranque en frío'],
  [/\bCold Start\b/gi, 'arranque en frío'],
  [/\bTorque Converter\b/gi, 'Convertidor de par'],
  [/\bSerial Communication Link\b/gi, 'Enlace de comunicación serial'],
  [/\bKeep Alive Memory\b/gi, 'Memoria KAM'],
  [/\bRead Only Memory\b/gi, 'Memoria ROM'],
  [/\bRandom Access Memory\b/gi, 'Memoria RAM'],
  [/\bGlow Plug\b/gi, 'Bujía incandescente'],
  [/\bAir Conditioner\b/gi, 'Aire acondicionado'],
  [/\bMalfunction Indicator Lamp\b/gi, 'Testigo de falla (MIL)'],
  [/\bLower Than Expected\b/gi, 'más bajo de lo esperado'],
  [/\bHigher Than Expected\b/gi, 'más alto de lo esperado'],
  [/\bThan Expected\b/gi, 'de lo esperado'],
  [/\bOver Temperature\b/gi, 'sobretemperatura'],
  [/\bEngine Overtemp\b/gi, 'Sobretemperatura del motor'],
  [/\bCooling System\b/gi, 'Sistema de refrigeración'],
  [/\bIgnition Switching\b/gi, 'Conmutación de encendido'],
  [/\bCam Position\b/gi, 'Posición del árbol de levas'],
  [/\bCharging System\b/gi, 'Sistema de carga'],

  [/\bInjection Pump Fuel Metering Control\b/gi, 'Control de dosificación de la bomba de inyección'],
  [/\bFuel Rail Pressure Sensor\b/gi, 'Sensor de presión del riel de combustible'],
  [/\bInjection Timing Control\b/gi, 'Control de sincronización de inyección'],
  [/\bEvaporative Emission Control System Pressure Sensor\b/gi, 'Sensor de presión del sistema EVAP'],
  [/\bTurbocharger Boost Sensor\b/gi, 'Sensor de presión de turbo'],
  [/\bEngine Oil Temperature Sensor\b/gi, 'Sensor de temperatura del aceite'],
  [/\bTransmission Fluid Temperature Sensor\b/gi, 'Sensor de temperatura del aceite de transmisión'],
  [/\bPressure Control Solenoid\b/gi, 'Solenoide de control de presión'],
  [/\bBrake Fluid Level\b/gi, 'Nivel de líquido de frenos'],
  [/\bIgnition Coil ([A-Z])\b/gi, 'Bobina de encendido $1'],
  [/\bEngine Coolant Level\b/gi, 'Nivel de refrigerante'],

  [/\bOutput Speed Sensor\b/gi, 'Sensor de velocidad de salida'],
  [/\bInput Speed Sensor\b/gi, 'Sensor de velocidad de entrada'],
  [/\bTurbine Speed Sensor\b/gi, 'Sensor de velocidad de turbina'],
  [/\bWheel Speed Sensor\b/gi, 'Sensor de velocidad de rueda'],
  [/\bGear (\d) Incorrect Ratio\b/gi, 'Relación incorrecta en $1ª marcha'],
  [/\bReverse Incorrect Gear Ratio\b/gi, 'Relación incorrecta en reversa'],
  [/\bTorque Converter Clutch Circuit Electrical\b/gi, 'Circuito eléctrico del embrague del convertidor'],

  // componentes (frases)
  [/\bMass or Volume Air Flow\b/gi, 'Sensor de flujo de aire (MAF)'],
  [/\bMass Air Flow\b/gi, 'Sensor de flujo de aire (MAF)'],
  [/\bManifold Absolute Pressure\/Barometric Pressure\b/gi, 'Presión absoluta del múltiple (MAP)/barométrica'],
  [/\bManifold Absolute Pressure\b/gi, 'Presión absoluta del múltiple (MAP)'],
  [/\bBarometric Pressure\b/gi, 'Presión barométrica'],
  [/\bIntake Air Temperature\b/gi, 'Temperatura del aire de admisión (IAT)'],
  [/\bEngine Coolant Temperature\b/gi, 'Temperatura del refrigerante (ECT)'],
  [/\bInsufficient Coolant Temperature for Closed Loop Fuel Control\b/gi, 'Temperatura de refrigerante insuficiente para lazo cerrado'],
  [/\bInsufficient Coolant Temperature for Stable Operation\b/gi, 'Temperatura de refrigerante insuficiente (termostato)'],
  [/\bThrottle\/Pedal Position Sensor\/Switch\b/gi, 'Sensor/interruptor de posición del acelerador (TPS)'],
  [/\bThrottle Position Sensor\/Switch\b/gi, 'Sensor/interruptor de posición del acelerador (TPS)'],
  [/\bThrottle Actuator Control\b/gi, 'Control del acelerador electrónico'],
  [/\bThrottle Position\b/gi, 'Posición del acelerador'],
  [/\bO2 Sensor Heater\b/gi, 'Calentador del sensor de oxígeno (O2)'],
  [/\bO2 Sensor\b/gi, 'Sensor de oxígeno (O2)'],
  [/\bHeated Oxygen Sensor\b/gi, 'Sensor de oxígeno calentado'],
  [/\bSystem Too Lean\b/gi, 'Mezcla muy pobre'],
  [/\bSystem Too Rich\b/gi, 'Mezcla muy rica'],
  [/\bFuel Trim System Lean\b/gi, 'Ajuste de combustible pobre'],
  [/\bFuel Trim System Rich\b/gi, 'Ajuste de combustible rico'],
  [/\bFuel Trim\b/gi, 'Ajuste de combustible'],
  [/\bFuel Rail Pressure\b/gi, 'Presión del riel de combustible'],
  [/\bFuel Pressure Regulator\b/gi, 'Regulador de presión de combustible'],
  [/\bFuel Pump\b/gi, 'Bomba de combustible'],
  [/\bFuel Level Sensor\b/gi, 'Sensor de nivel de combustible'],
  [/\bFuel Temperature Sensor\b/gi, 'Sensor de temperatura de combustible'],
  [/\bFuel Injector\b/gi, 'Inyector'],
  [/\bInjector Circuit\b/gi, 'Circuito del inyector'],
  [/\bRandom\/Multiple Cylinder Misfire\b/gi, 'Fallo de encendido aleatorio/múltiple'],
  [/\bCylinder (\d+) Misfire\b/gi, 'Fallo de encendido en cilindro $1'],
  [/\bMisfire\b/gi, 'Fallo de encendido'],
  [/\bKnock Sensor\b/gi, 'Sensor de detonación (knock)'],
  [/\bCrankshaft Position Sensor\b/gi, 'Sensor de posición del cigüeñal (CKP)'],
  [/\bCamshaft Position Sensor\b/gi, 'Sensor de posición del árbol de levas (CMP)'],
  [/\bCrankshaft Position\b/gi, 'Posición del cigüeñal'],
  [/\bCamshaft Position\b/gi, 'Posición del árbol de levas'],
  [/\bIgnition Coil\b/gi, 'Bobina de encendido'],
  [/\bExhaust Gas Recirculation\b/gi, 'Recirculación de gases de escape (EGR)'],
  [/\bCatalyst System Efficiency\b/gi, 'Eficiencia del catalizador'],
  [/\bWarm Up Catalyst Efficiency\b/gi, 'Eficiencia del catalizador de arranque'],
  [/\bMain Catalyst Efficiency\b/gi, 'Eficiencia del catalizador principal'],
  [/\bEvaporative Emission Control System\b/gi, 'Sistema de emisiones evaporativas (EVAP)'],
  [/\bPurge Control Valve\b/gi, 'Válvula de purga'],
  [/\bVent Control\b/gi, 'Control de ventilación'],
  [/\bLeak Detected \(small leak\)\b/gi, 'fuga pequeña detectada'],
  [/\bLeak Detected \(gross leak\)\b/gi, 'fuga grande detectada'],
  [/\bLeak Detected\b/gi, 'fuga detectada'],
  [/\bVehicle Speed Sensor\b/gi, 'Sensor de velocidad del vehículo (VSS)'],
  [/\bIdle Control System\b/gi, 'Sistema de control de ralentí'],
  [/\bIdle Air Control\b/gi, 'Control de aire de ralentí (IAC)'],
  [/\bClosed Throttle Position Switch\b/gi, 'Interruptor de acelerador cerrado'],
  [/\bSystem Voltage\b/gi, 'Voltaje del sistema'],
  [/\bInternal Control Module\b/gi, 'Módulo de control interno'],
  [/\bControl Module\b/gi, 'Módulo de control'],
  [/\bTransmission Range Sensor\b/gi, 'Sensor de rango de transmisión'],
  [/\bTransmission Fluid Temperature\b/gi, 'Temperatura del aceite de transmisión'],
  [/\bTorque Converter Clutch\b/gi, 'Embrague del convertidor de par'],
  [/\bShift Solenoid\b/gi, 'Solenoide de cambio'],
  [/\bShift\/Timing Solenoid\b/gi, 'Solenoide de cambio/sincronización'],
  [/\bTurbocharger\/Supercharger\b/gi, 'Turbo/supercargador'],
  [/\bTurbocharger Wastegate\b/gi, 'Wastegate del turbo'],
  [/\bTurbocharger Boost\b/gi, 'Presión de turbo'],
  [/\bTurbocharger\b/gi, 'Turbocompresor'],
  [/\bA\/C Refrigerant Pressure Sensor\b/gi, 'Sensor de presión del refrigerante A/C'],
  [/\bSecondary Air Injection System\b/gi, 'Sistema de inyección de aire secundario'],
  [/\bTiming Reference High Resolution Signal\b/gi, 'Señal de referencia de sincronización de alta resolución'],
  [/\bIgnition\/Distributor Engine Speed Input\b/gi, 'Señal de RPM de encendido/distribuidor'],
  [/\bEngine Speed Input\b/gi, 'Señal de RPM del motor'],
  [/\bCruise Control\b/gi, 'Control crucero'],
  [/\bEngine Oil Temperature\b/gi, 'Temperatura del aceite del motor'],
  [/\bCooling Fan\b/gi, 'Electroventilador'],
  [/\bBrake Switch\b/gi, 'Interruptor de freno'],
  [/\bClutch Switch\b/gi, 'Interruptor de embrague'],
  [/\bPower Steering Pressure Sensor\b/gi, 'Sensor de presión de dirección hidráulica'],
  [/\bGear (\d+) Incorrect Ratio\b/gi, 'Relación incorrecta en $1ª marcha'],
  [/\bIncorrect Gear Ratio\b/gi, 'Relación de cambio incorrecta'],
  [/\bEngine Coolant Blower Motor\b/gi, 'Motor del ventilador de refrigeración'],
  [/\bGenerator\b/gi, 'Alternador'],
  [/\bStarter\b/gi, 'Motor de arranque'],
  [/\bReverse Inhibit Control\b/gi, 'Control de inhibición de reversa'],
  [/\b(\d)-(\d) Shift\b/gi, 'Cambio $1-$2'],
  [/\b(\d)-(\d) Upshift \(Skip Shift\) Solenoid Control\b/gi, 'Solenoide de salto de cambio $1-$2'],
  [/\b(\d)-(\d) Upshift \(Skip Shift\) Lamp Control\b/gi, 'Testigo de salto de cambio $1-$2'],
  [/\bNormal\/Performance Switch\b/gi, 'Interruptor normal/desempeño'],
  [/\bContribution\/Range Fault\b/gi, '— contribución/rango fuera de especificación'],
  [/\bBalance Fault\b/gi, '— desbalance'],
  [/\bCylinder (\d+)\b/gi, 'Cilindro $1'],
  [/\bBank (\d+) Sensor (\d+)\b/gi, 'Banco $1 Sensor $2'],
  [/\bBank (\d+)\b/gi, 'Banco $1'],
  [/\bSensor (\d+)\b/gi, 'Sensor $1'],

  // condiciones de circuito (sufijos)
  [/\bCircuit Range\/Performance( Problem)?\b/gi, '§CIRC§ — rango/desempeño fuera de especificación'],
  [/\bRange\/Performance( Problem)?\b/gi, '— rango/desempeño fuera de especificación'],
  [/\bCircuit Low Input\b/gi, '§CIRC§ — señal baja'],
  [/\bCircuit High Input\b/gi, '§CIRC§ — señal alta'],
  [/\bCircuit Low Voltage\b/gi, '§CIRC§ — voltaje bajo'],
  [/\bCircuit High Voltage\b/gi, '§CIRC§ — voltaje alto'],
  [/\bCircuit Slow Response\b/gi, '§CIRC§ — respuesta lenta'],
  [/\bCircuit No Activity Detected\b/gi, '§CIRC§ — sin actividad'],
  [/\bCircuit Intermittent\b/gi, '§CIRC§ — señal intermitente'],
  [/\bCircuit Malfunction\b/gi, '§CIRC§ — falla'],
  [/\bCircuit Shorted\b/gi, '§CIRC§ — en corto'],
  [/\bCircuit Open\b/gi, '§CIRC§ — abierto'],
  [/\bCircuit Low\b/gi, '§CIRC§ — señal baja'],
  [/\bCircuit High\b/gi, '§CIRC§ — señal alta'],
  [/\bCircuit\b/gi, '§CIRC§'],
  [/\bLow Input\b/gi, '— señal baja'],
  [/\bHigh Input\b/gi, '— señal alta'],
  [/\bNo Signal\b/gi, '— sin señal'],
  [/\bIntermittent\b/gi, '— intermitente'],
  [/\bMalfunction\b/gi, '— falla'],
  [/\bStuck Open\b/gi, '— atascado abierto'],
  [/\bStuck Closed\b/gi, '— atascado cerrado'],
  [/\bStuck Off\b/gi, '— atascado apagado'],
  [/\bStuck On\b/gi, '— atascado encendido'],
  [/\bToo Few Pulses\b/gi, '— pulsos insuficientes'],
  [/\bToo Many Pulses\b/gi, '— demasiados pulsos'],
  [/\bIncorrect Purge Flow\b/gi, '— flujo de purga incorrecto'],
  [/\bBelow Threshold\b/gi, 'bajo el umbral'],
  [/\bNo Activity Detected\b/gi, '— sin actividad'],
  [/\bSlow Response\b/gi, '— respuesta lenta'],
  [/\bNot Detected\b/gi, '— no detectado'],
  [/\bDetected\b/gi, 'detectado'],

  // palabras sueltas restantes
  [/\bSensor\b/gi, 'Sensor'],
  [/\bSwitch\b/gi, 'Interruptor'],
  [/\bSolenoid\b/gi, 'Solenoide'],
  [/\bValve\b/gi, 'Válvula'],
  [/\bPressure\b/gi, 'Presión'],
  [/\bTemperature\b/gi, 'Temperatura'],
  [/\bPosition\b/gi, 'Posición'],
  [/\bSpeed\b/gi, 'Velocidad'],
  [/\bSignal\b/gi, 'Señal'],
  [/\bVoltage\b/gi, 'Voltaje'],
  [/\bSystem\b/gi, 'Sistema'],
  [/\bControl\b/gi, 'Control'],
  [/\bEngine\b/gi, 'Motor'],
  [/\bFuel\b/gi, 'Combustible'],
  [/\bAir Flow\b/gi, 'Flujo de aire'],
  [/\bFlow\b/gi, 'Flujo'],
  [/\bAir\b/gi, 'Aire'],
  [/\bExhaust\b/gi, 'Escape'],
  [/\bIntake\b/gi, 'Admisión'],
  [/\bIgnition\b/gi, 'Encendido'],
  [/\bTiming\b/gi, 'Sincronización'],
  [/\bInjection\b/gi, 'Inyección'],
  [/\bInjector\b/gi, 'Inyector'],
  [/\bTransmission\b/gi, 'Transmisión'],
  [/\bClutch\b/gi, 'Embrague'],
  [/\bPump\b/gi, 'Bomba'],
  [/\bCoil\b/gi, 'Bobina'],
  [/\bLevel\b/gi, 'Nivel'],
  [/\bPrimary\b/gi, 'primario'],
  [/\bSecondary\b/gi, 'secundario'],
  [/\bPerformance\b/gi, 'desempeño'],
  [/\bRange\b/gi, 'rango'],
  [/\bFault\b/gi, 'falla'],
  [/\bCatalyst\b/gi, 'Catalizador'],
  [/\bThrottle\b/gi, 'Acelerador'],
  [/\bPedal\b/gi, 'Pedal'],
  [/\bOxygen\b/gi, 'Oxígeno'],
  [/\bHeater\b/gi, 'Calentador'],
  [/\bLamp\b/gi, 'Testigo'],
  [/\bModule\b/gi, 'Módulo'],
  [/\bMemory\b/gi, 'Memoria'],
  [/\bProcessor\b/gi, 'Procesador'],
  [/\bBattery\b/gi, 'Batería'],
  [/\bPower\b/gi, 'Alimentación'],
  [/\bGround\b/gi, 'Tierra'],
  [/\bRelay\b/gi, 'Relé'],
  [/\bMotor\b/gi, 'Motor'],
  [/\bGear\b/gi, 'Marcha'],
  [/\bRatio\b/gi, 'Relación'],
  [/\bFrequency\b/gi, 'Frecuencia'],
  [/\bReference\b/gi, 'Referencia'],
  [/\bResolution\b/gi, 'Resolución'],
  [/\bPulses?\b/gi, 'Pulsos'],
  [/\bMetering\b/gi, 'Medición'],
  [/\bRecirculation\b/gi, 'Recirculación'],
  [/\bEmission\b/gi, 'Emisiones'],
  [/\bEvaporative\b/gi, 'Evaporativo'],
  [/\bLeak\b/gi, 'Fuga'],
  [/\bPurge\b/gi, 'Purga'],
  [/\bVent\b/gi, 'Ventilación'],
  [/\bThreshold\b/gi, 'Umbral'],
  [/\bEfficiency\b/gi, 'Eficiencia'],
  [/\bIdle\b/gi, 'Ralentí'],
  [/\bVehicle\b/gi, 'Vehículo'],
  [/\bInternal\b/gi, 'Interno'],
  [/\bExternal\b/gi, 'Externo'],
  [/\bCircuit\b/gi, 'Circuito'],
  [/\bOpen\b/gi, 'abierto'],
  [/\bShorted\b/gi, 'en corto'],
  [/\bShort\b/gi, 'corto'],
  [/\bHigh\b/gi, 'alto'],
  [/\bLow\b/gi, 'bajo'],
  [/\bInput\b/gi, 'entrada'],
  [/\bOutput\b/gi, 'salida'],
  [/\bDetected\b/gi, 'detectado'],
  [/\bClosed Loop\b/gi, 'lazo cerrado'],
  [/\bClosed\b/gi, 'cerrado'],
  [/\bStuck\b/gi, 'atascado'],
  [/\bIncorrect\b/gi, 'incorrecto'],
  [/\bInsufficient\b/gi, 'insuficiente'],
  [/\bExcessive\b/gi, 'excesivo'],
  [/\bBelow\b/gi, 'bajo'],
  [/\bAbove\b/gi, 'sobre'],
  [/\bToo\b/gi, 'muy'],
  [/\bLean\b/gi, 'pobre'],
  [/\bRich\b/gi, 'rica'],
  [/\bMalfunction\b/gi, 'falla'],
  [/\bCondition\b/gi, 'condición'],
  [/\bRequested\b/gi, 'solicitado'],
  [/\bDriver\b/gi, 'Manejador'],
  [/\bBank\b/gi, 'Banco'],
  [/\bCylinder\b/gi, 'Cilindro'],
  [/\bWastegate\b/gi, 'Wastegate'],
  [/\bBoost\b/gi, 'Presión de turbo'],
  [/\bBrake\b/gi, 'Freno'],
  [/\bCooling\b/gi, 'Refrigeración'],
  [/\bCoolant\b/gi, 'Refrigerante'],
  [/\bOil\b/gi, 'Aceite'],
  [/\bMass\b/gi, 'Masa'],
  [/\bVolume\b/gi, 'Volumen'],
  [/\bManifold\b/gi, 'Múltiple'],
  [/\bAbsolute\b/gi, 'Absoluta'],
  [/\bBarometric\b/gi, 'Barométrica'],
  [/\bDistributor\b/gi, 'Distribuidor'],
  [/\bAlternator\b/gi, 'Alternador'],
  [/\bSteering\b/gi, 'Dirección'],
  [/\bSupercharger\b/gi, 'Supercargador'],
  [/\bRefrigerant\b/gi, 'Refrigerante'],
  [/\bWarm Up\b/gi, 'de arranque'],
  [/\bAuxiliary\b/gi, 'auxiliar'],
  [/\bEmissions?\b/gi, 'Emisiones'],
  [/\bRandom\b/gi, 'aleatorio'],
  [/\bMultiple\b/gi, 'múltiple'],
  [/\bContribution\b/gi, 'Contribución'],
  [/\bBalance\b/gi, 'Balance'],
  [/\bResponse\b/gi, 'Respuesta'],
  [/\bActivity\b/gi, 'Actividad'],
  [/\bSlow\b/gi, 'lenta'],
  [/\bFew\b/gi, 'pocos'],
  [/\bMany\b/gi, 'muchos'],
  [/\bNo\b/gi, 'sin'],
  [/\band\b/gi, 'y'],
  [/\bor\b/gi, 'o'],
  [/\bfor\b/gi, 'para'],
  [/\bof\b/gi, 'de'],
  [/\bthe\b/gi, 'el'],
  [/\bin\b/gi, 'en'],
  [/\bto\b/gi, 'a'],
  [/\bElectrical\b/gi, 'eléctrico'],
  [/\bSwitching\b/gi, 'conmutación'],
  [/\bRelated\b/gi, 'relacionado'],
  [/\bError\b/gi, 'error'],
  [/\bComposition\b/gi, 'composición'],
  [/\bHeated\b/gi, 'calentado'],
  [/\bTurbine\b/gi, 'turbina'],
  [/\bErratic\b/gi, 'errático'],
  [/\bShutoff\b/gi, 'corte'],
  [/\bOverspeed\b/gi, 'sobrevelocidad'],
  [/\bOverboost\b/gi, 'sobrepresión de turbo'],
  [/\bOvertemp\b/gi, 'sobretemperatura'],
  [/\bRationality\b/gi, 'racionalidad'],
  [/\bCurrent\b/gi, 'corriente'],
  [/\bCharge\b/gi, 'carga'],
  [/\bLoss\b/gi, 'pérdida'],
  [/\bUnstable\b/gi, 'inestable'],
  [/\bResume\b/gi, 'reanudar'],
  [/\bCoast\b/gi, 'desaceleración'],
  [/\bAccel\b/gi, 'aceleración'],
  [/\bProgramming\b/gi, 'programación'],
  [/\bAccess\b/gi, 'acceso'],
  [/\bField\b/gi, 'campo'],
  [/\bReverse\b/gi, 'reversa'],
  [/\bShift\b/gi, 'Cambio'],
  [/\bIndicator\b/gi, 'indicador'],
  [/\bCheck\b/gi, 'revisión'],
  [/\bRotor\b/gi, 'rotor'],
  [/\bCam\b/gi, 'árbol de levas'],
  [/\bCamshaft\b/gi, 'árbol de levas'],
  [/\bCrankshaft\b/gi, 'cigüeñal'],
  [/\bHot\b/gi, 'caliente'],
  [/\bCold\b/gi, 'frío'],
  [/\bStart\b/gi, 'arranque'],
  [/\bOver\b/gi, 'sobre'],
  [/\bOn\b/gi, 'encendido'],
  [/\bOff\b/gi, 'apagado'],
  [/\bSet\b/gi, 'fijar'],
  [/\bSum\b/gi, 'suma'],
  [/\bPlug\b/gi, 'bujía'],
  [/\bGlow\b/gi, 'incandescente'],
  [/\bConditioner\b/gi, 'acondicionado'],
  [/\bLower\b/gi, 'menor'],
  [/\bHigher\b/gi, 'mayor'],
  [/\bExpected\b/gi, 'esperado'],
  [/\bThan\b/gi, 'que'],
  [/\bLink\b/gi, 'enlace'],
  [/\bCommunication\b/gi, 'comunicación'],
  [/\bSerial\b/gi, 'serial'],
  [/\bAlive\b/gi, 'activa'],
  [/\bKeep\b/gi, 'mantener'],
  [/\bOnly\b/gi, 'solo'],
  [/\bRead\b/gi, 'lectura'],
  [/\bTorque\b/gi, 'par'],
  [/\bConverter\b/gi, 'convertidor'],
];

function traducir(en) {
  let s = ' ' + normalizar(en) + ' ';
  for (const [re, rep] of FRASES) s = s.replace(re, rep);
  return s
    .replace(/§CIRC§/g, '')          // "Circuit" queda implícito en español
    .replace(/\s*—\s*/g, ' — ')
    .replace(/\s+/g, ' ')
    .replace(/\s+([),])/g, '$1')
    .replace(/\(\s+/g, '(')
    .replace(/ — $/, '')
    .trim();
}

/* 3. Traducir y verificar que no quede inglés */
const INGLES_OK = /^(A|B|C|D|I|II|III|O2|MAF|MAP|IAT|ECT|TPS|CKP|CMP|EGR|EVAP|VSS|IAC|PRNDL|PCM|ECM|TCM|ABS|SAE|A\/C|W)$/;
const salida = {};
const sospechosos = [];
for (const [codigo, descEn] of crudos) {
  const es = traducir(descEn);
  salida[codigo] = es;
  // cualquier token alfabético que siga pareciendo inglés
  for (const tok of es.match(/[A-Za-z][A-Za-z']+/g) || []) {
    if (INGLES_OK.test(tok)) continue;
    if (/[áéíóúñ]/i.test(tok)) continue;
    if (!/^(Sensor|Motor|Control|Banco|Cilindro|Balance|Nivel|Pedal|Total|Turbo|Wastegate|Normal|Interruptor|Bomba|Bobina|Relé|Marcha|Umbral|Pulsos|Umbral)$/i.test(tok)
        && /^(a|about|above|actuator|assembly|bank|below|circuit|closed|control|cylinder|detected|excessive|fault|flow|for|gear|ground|high|in|input|insufficient|intermittent|lamp|leak|lean|level|low|malfunction|mass|metering|misfire|module|no|of|open|or|output|performance|position|power|pressure|primary|pulse|pulses|purge|random|range|ratio|reference|refrigerant|relay|requested|resolution|response|rich|secondary|sensor|shift|short|shorted|signal|slow|solenoid|speed|stuck|switch|system|temperature|the|threshold|throttle|timing|to|too|valve|vehicle|vent|voltage|volume)$/i.test(tok)) {
      sospechosos.push([codigo, descEn, es, tok]);
    }
  }
}

console.log('Códigos traducidos:', Object.keys(salida).length);
if (sospechosos.length) {
  console.log('\n*** QUEDÓ INGLÉS SIN TRADUCIR (' + sospechosos.length + ') ***');
  sospechosos.slice(0, 25).forEach(([c, en, es, t]) => console.log(`  ${c} [${t}]  ${en}  =>  ${es}`));
  process.exitCode = 1;
} else {
  console.log('✓ Sin palabras en inglés pendientes');
}
fs.writeFileSync(T + 'dtc_es.json', JSON.stringify(salida, null, 0));

console.log('\n--- muestra ---');
['P0101','P0113','P0128','P0131','P0171','P0300','P0304','P0325','P0335','P0401','P0420','P0442','P0455','P0500','P0700','P0741','P0246']
  .forEach(c => salida[c] && console.log(c.padEnd(6), salida[c]));
