const fs=require('fs'),vm=require('vm'),path=require('path');
const {ok,fin}=require('./harness');
const ctx={globalThis:null,Modulos:{},console}; ctx.globalThis=ctx; vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(__dirname,'../../js/modulos/operacion/diagnostico_oem.js'),'utf8'),ctx);
const O=ctx.OEMMotor;
const base={nombre:'Temperatura',marca:'Ford',ecu:'PCM',tipo:'did',identificador:'1234',fuente:'Manual OEM',estado:'verificado',riesgo:'lectura',activa:true};
ok('expone el motor OEM',!!O);
ok('acepta una lectura DID trazable',O.validar(base).length===0);
ok('rechaza DID mal formado',O.validar({...base,identificador:'12ZZ'}).some(x=>x.includes('DID')));
ok('rechaza acción no verificada',O.validar({...base,tipo:'purga_abs',estado:'laboratorio',riesgo:'alto'}).some(x=>x.includes('verificado')));
ok('permite ejecutar solo lectura verificada',O.puedeEjecutar(base).ok===true);
ok('bloquea una prueba activa aunque figure verificada',O.puedeEjecutar({...base,tipo:'prueba_activa',riesgo:'controlado'}).ok===false);
ok('filtra por marca/modelo/año',O.aplica({...base,modelo:'F-150',anio_desde:2015,anio_hasta:2020},{marca:'ford',modelo:'f-150',anio:2017}));
ok('no aplica fuera del año',!O.aplica({...base,anio_desde:2015},{marca:'Ford',anio:2010}));
ok('decodifica ASCII',O.decodificar([0x41,0x42],{tipo:'ascii'})==='AB');
ok('aplica escala y offset',O.decodificar([0,10],{tipo:'numero',escala:0.5,offset:-2})===3);
ok('declara cinco canales',O.canales.length===5);
ok('solo HS está operativo',O.canales.filter(x=>x.estado==='operativo').map(x=>x.id).join(',')==='hs');
ok('la arquitectura incluye BLE, RP1210, J2534, SDK de fabricante y VCI',O.familias.map(x=>x.id).join(',')==='elm,rp1210,j2534,fabricante,vci');
fin();
