const fs=require('fs'),vm=require('vm'),path=require('path');
const {ok,fin}=require('./harness');
const fuenteOEM=fs.readFileSync(path.join(__dirname,'../../js/modulos/operacion/diagnostico_oem.js'),'utf8');
const ctx={globalThis:null,Modulos:{},console}; ctx.globalThis=ctx; vm.createContext(ctx);
vm.runInContext(fuenteOEM,ctx);
const O=ctx.OEMMotor;
const base={nombre:'Temperatura',marca:'Ford',ecu:'PCM',tipo:'did',identificador:'1234',fuente:'Manual OEM',estado:'verificado',riesgo:'lectura',activa:true};
ok('expone el motor OEM',!!O);
ok('acepta una lectura DID trazable',O.validar(base).length===0);
ok('rechaza DID mal formado',O.validar({...base,identificador:'12ZZ'}).some(x=>x.includes('DID')));
ok('rechaza acción no verificada',O.validar({...base,tipo:'purga_abs',estado:'laboratorio',riesgo:'alto'}).some(x=>x.includes('verificado')));
ok('permite ejecutar solo lectura verificada',O.puedeEjecutar(base).ok===true);
ok('bloquea una prueba activa aunque figure verificada',O.puedeEjecutar({...base,tipo:'prueba_activa',riesgo:'controlado'}).ok===false);
ok('filtra por marca/modelo/año',O.aplica({...base,modelo:'F-150',anio_desde:2015,anio_hasta:2020},{marca:'ford',modelo:'f-150',anio:2017}));
ok('no aplica fuera del año',!O.aplica({...base,anio_desde:2015},{marca:'Ford',anio:2010}));
ok('decodifica ASCII',O.decodificar([0x41,0x42],{tipo:'ascii'})==='AB');
ok('aplica escala y offset',O.decodificar([0,10],{tipo:'numero',escala:0.5,offset:-2})===3);
ok('declara cinco canales',O.canales.length===5);
ok('solo HS está operativo',O.canales.filter(x=>x.estado==='operativo').map(x=>x.id).join(',')==='hs');
ok('la arquitectura incluye BLE, RP1210, J2534, SDK de fabricante y VCI',O.familias.map(x=>x.id).join(',')==='elm,rp1210,j2534,fabricante,vci');
ok('describe propiedades BLE sin inventar las ausentes',O.propsBLE({read:true,notify:true,write:false}).join(',')==='read,notify');
const topo=O.construirTopologia([{id:'hs',modulos:[{req:2016,resp:2024,nombre:'PCM'},{req:2016,resp:2024,nombre:'duplicado'},{req:'x',resp:1}]}],{modo:'real'});
ok('construye las cinco redes y deduplica módulos',topo.redes.length===5&&topo.total_modulos===1&&topo.redes[0].modulos[0].nombre==='duplicado');
ok('distingue redes no escaneadas',topo.redes.find(x=>x.id==='ms').estado==='no_escaneada');
const ford=O.simularTopologia('ford');
ok('simulador Ford produce topología marcada y multired',ford.modo==='simulador'&&ford.total_modulos===5&&ford.redes.find(x=>x.id==='ms').estado==='simulada');
const gm=O.simularTopologia('gm');
ok('simulador GM incluye SW-CAN sin habilitarla como real',gm.redes.find(x=>x.id==='sw').modulos.length===2&&gm.redes.find(x=>x.id==='sw').modulos.every(x=>x.simulado));
ok('paquete base expone DIDs UDS trazables',O.didsBase.map(x=>x.did).join(',')==='F190,F187,F189,F18C'&&O.didsBase.every(x=>x.fuente));
ok('incluye simuladores de marcas comunes en Guatemala',['toyota','nissan','hyundai_kia','mitsubishi','isuzu'].every(x=>O.perfilesSimulados[x]));
ok('catálogo guiado incluye marcas, ECUs y protocolos',O.marcas.includes('Toyota')&&O.marcas.includes('Isuzu')&&O.ecus.some(x=>x.includes('ABS'))&&O.protocolos.includes('j1939'));
ok('rechaza una red fuera del catálogo',O.validar({...base,protocolo:'uds',definicion:{red:'inventada'}}).some(x=>x.includes('Red')));
ok('genera referencias para los siete vehículos de prueba',O.referenciasVehiculos.length===42&&O.referenciasVehiculos.filter(x=>x.tipo==='did').length===28);
ok('las referencias IMMO son sólo diagnósticas',O.referenciasVehiculos.filter(x=>x.tipo==='immo_diagnostico').every(x=>x.definicion.objetivo_immo==='identificacion'&&x.estado==='borrador'));
ok('las referencias de mantenimiento son borradores',O.referenciasVehiculos.filter(x=>x.tipo==='reset').every(x=>x.definicion.objetivo_reset==='mantenimiento'&&x.estado==='borrador'));
ok('rechaza un rango de años invertido',O.validar({...base,anio_desde:2020,anio_hasta:2010}).some(x=>x.includes('año')));
ok('precondiciones aprobadas con estado confirmado',O.evaluarPrecondiciones([{clave:'motor',valor:false},{clave:'velocidad_max',valor:0},{clave:'voltaje_min',valor:12}],{motor:false,velocidad:0,voltaje:12.6}).ok);
ok('precondición sin telemetría bloquea, no adivina',!O.evaluarPrecondiciones([{clave:'freno',valor:true}],{}).ok);
ok('precondición desconocida se bloquea',O.evaluarPrecondiciones([{clave:'misterio',valor:1}],{}).fallos[0].includes('desconocida'));
ok('catálogo incluye resets de ABS, TPMS y módulos',['abs_aprendizajes','tpms_reaprendizaje','ecu_reinicio'].every(x=>O.objetivosReset.some(y=>y.id===x)));
ok('reset sin objetivo guiado se rechaza',O.validar({...base,tipo:'reset',riesgo:'alto'}).some(x=>x.includes('objetivo')));
ok('reset verificado sigue sin transmitirse en esta etapa',!O.puedeEjecutar({...base,tipo:'reset',riesgo:'alto',definicion:{objetivo_reset:'ecu_reinicio'}}).ok);
ok('reporte de parámetros ofrece guardar PDF',fuenteOEM.includes('Guardar PDF / imprimir')&&fuenteOEM.includes('imprimirParametrosOEM'));
const fuenteOBD=fs.readFileSync(path.join(__dirname,'../../js/modulos/operacion/diagnostico_obd.js'),'utf8');
ok('borrado general exige copia previa',/borrarDTCs[\s\S]*?_guardarAntesDeBorrar\(\)[\s\S]*?if \(!guardado\)/.test(fuenteOBD));
ok('borrado por módulo cancela si falla el historial',/borrarPorModulo[\s\S]*?_guardarAntesDeBorrar\(\)[\s\S]*?if \(!guardado\)/.test(fuenteOBD));
ok('IMMO ofrece diagnóstico y aprendizaje autorizado',O.objetivosImmo.some(x=>x.id==='estado_llave')&&O.objetivosImmo.some(x=>x.id==='reaprendizaje_oem'));
ok('IMMO no ofrece clonación ni bypass',!O.objetivosImmo.some(x=>/clon|bypass|secreto/i.test(x.id+' '+x.nombre)));
ok('programación IMMO real permanece bloqueada',!O.puedeEjecutar({...base,tipo:'immo_programacion',riesgo:'critico',definicion:{objetivo_immo:'reaprendizaje_oem'}}).ok);
ok('plan incluye la flota real de pruebas',O.planValidacion.length===7&&O.planValidacion.some(x=>x.id==='international_dt466'));
ok('pruebas activas tienen objetivos guiados',O.objetivosActivos.some(x=>x.id==='ventilador')&&O.objetivosActivos.every(x=>x.precondiciones.length));
ok('preparación activa exige estado verificado',!O.puedePrepararActiva({tipo:'prueba_activa',estado:'laboratorio',riesgo:'controlado',definicion:{objetivo_activo:'bocina'}},{contacto:true}).ok);
ok('preparación activa acepta precondiciones confirmadas',O.puedePrepararActiva({tipo:'prueba_activa',estado:'verificado',riesgo:'controlado',definicion:{objetivo_activo:'bocina'}},{contacto:true}).ok);
fin();
