const { cargar, ok, fin } = require('./harness');
const fs = require('fs');
const vm = require('vm');
const path = require('path');
const crypto = require('crypto');
const { M, ctx } = cargar({crypto});
for (const f of ['diagnostico_modulos.js','diagnostico_transporte.js'])
  vm.runInContext(fs.readFileSync(path.join(__dirname,'../../js/modulos/operacion',f),'utf8'),ctx);
ctx.UI.esc = s => String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
ctx.Modulos.btnAccion = (tipo,accion) => `<button onclick="${accion}">${tipo}</button>`;
let html='', titulo='';
ctx.UI.modal=(t,h)=>{titulo=t;html=h;};
const vacio = () => ({vehiculo_id:'v1',categoria:'pesado',nodos:[],conexiones:[],revision:0});
async function main() {
  ok('motocicletas y scooters tienen familia propia',M._categoriaTransporte({tipo:'Motocicleta'})==='moto' && M._categoriaTransporte({tipo:'Scooter / Motojet'})==='moto');
  ok('no clasifica un motogenerador como motocicleta',M._categoriaTransporte({tipo:'Motogenerador'})!=='moto');
  ok('maquinaria agrícola y camiones se separan',M._categoriaTransporte({tipo:'Maquinaria Agrícola'})==='maquinaria' && M._categoriaTransporte({tipo:'Camión de reparto'})==='pesado');
  ok('catálogo incluye maquinaria y motocicletas',M._catalogoTransporte.maquinaria.marcas.includes('Komatsu') && M._catalogoTransporte.moto.marcas.includes('Bajaj'));
  const plantilla=M._plantillaTransporte('moto');
  ok('plantilla moto incluye ABS e IMU',plantilla.some(n=>n.sistema==='abs') && plantilla.some(n=>n.sistema==='imu'));
  ok('plantillas no inventan direcciones ni documentación',plantilla.every(n=>n.estado==='orientativo' && !n.direccion && !n.fuente));
  M._mapaTransporte=vacio(); M._mapaVehiculo={id:'v1'}; M._vehiculos=[M._mapaVehiculo];
  let guardados=0;
  ctx.DB.guardarTopologiaVehiculo=async m=>{guardados++;return {...m,id:'map1',revision:m.revision+1};};
  await M.agregarPlantillaMapa(); const cantidad=M._mapaTransporte.nodos.length;
  await M.agregarPlantillaMapa();
  ok('importar plantilla dos veces no duplica sistemas',M._mapaTransporte.nodos.length===cantidad);
  ok('SCR y DPF están en camión',M._mapaTransporte.nodos.some(n=>n.sistema==='scr') && M._mapaTransporte.nodos.some(n=>n.sistema==='dpf'));
  M._scan={vehiculo_id:'v1',por_modulo:[{ecu:2024,nombre:'Motor',respondio:true},{ecu:2025,nombre:'Sin respuesta',respondio:false}]};
  await M.importarScanMapa();await M.importarScanMapa();
  ok('importación idempotente solo agrega módulos que respondieron',M._mapaTransporte.nodos.length===cantidad+1);
  ok('importación no deduce cables',M._mapaTransporte.conexiones.length===0);
  const [a,b]=M._mapaTransporte.nodos;
  let rechazado=false;
  try {M._validarMapaTransporte({...vacio(),nodos:[a,b],conexiones:[{desde:a.id,hasta:'inexistente'}]});} catch(e) {rechazado=true;}
  ok('rechaza conexiones a módulo inexistente',rechazado);
  rechazado=false;
  try {M._validarMapaTransporte({...vacio(),nodos:[{...a,estado:'documentado',fuente:''}]});} catch(e) {rechazado=true;}
  ok('documentación exige fuente',rechazado);
  M._mapaTransporte.conexiones=[{id:'e',desde:a.id,hasta:b.id,red:'CAN',pines:'1 a 2',estado:'orientativo'}];
  ok('diagrama muestra enlaces pendientes sin declararlos verificados',M._diagramaTransporte(M._mapaTransporte).includes('stroke-dasharray'));
  await M.quitarElementoMapa('nodos',0);
  ok('eliminar módulo elimina enlaces dependientes',!M._mapaTransporte.nodos.some(n=>n.id===a.id) && !M._mapaTransporte.conexiones.length);
  const antes=JSON.stringify(M._mapaTransporte);
  ctx.DB.guardarTopologiaVehiculo=async()=>{throw new Error('conflicto de revisión');};
  await M._persistirMapa(m=>m.nodos.push({...a,id:'nuevo'}));
  ok('fallo de guardado conserva mapa anterior',JSON.stringify(M._mapaTransporte)===antes && ctx.toasts.some(t=>t.includes('conflicto')));
  ctx.puedeAccion=()=>false;
  const g=guardados;
  await M.agregarPlantillaMapa();
  ok('solo lectura no modifica mapa',guardados===g && JSON.stringify(M._mapaTransporte)===antes);
  ctx.puedeAccion=()=>true;
  const ruta=M._rutaTransporte('U0100','gateway').join(' ');
  ok('U0100 dirige a conexiones compartidas y limitación de protocolo',ruta.includes('ramal compartido') && ruta.includes('protocolo no soportado'));
  ok('SPN/FMI conserva origen y no receta cambio de pieza',M._rutaTransporte('SPN 100 FMI 1','ecm').join(' ').includes('dirección de origen'));
  M._mapaScan={dtcs:[{codigo:'P0300'}],por_modulo:[{nombre:'ABS',codigos:[{codigo:'C0035',activo:true}]}]};
  ok('ruta ofrece DTC del escaneo con módulo de origen',M._dtcsMapaHTML().includes('ABS · activo') && M._dtcsMapa.length===2);
  M._mapaTransporte.nodos[0].nombre='<img src=x onerror=alert(1)>';
  M._pintarMapaTransporte();
  ok('escapa texto no confiable en mapa',!html.includes('<img src=x') && html.includes('&lt;img'));
  M._centroScan={vehiculos:{marca:'Honda',modelo:'CB500'}};
  M.verGuia('P0300');
  ok('guía existente se abre sin ReferenceError y usa vehículo real',html.includes('Honda') && !html.includes('Accent'));
  M.verGuia('P1999');
  ok('DTC sin guía muestra orientación sin inventar reparación',html.includes('Todavía no hay guía'));
  ctx.DB.getVehiculos=async()=>[{id:'m1',tipo:'Motocicleta',marca:'Honda'},{id:'c1',tipo:'Pesado / Tráiler',marca:'Hino'}];
  await M.modalMotocicletas();
  ok('botón moto muestra solamente motocicletas',html.includes('Honda') && !html.includes('Hino') && titulo.includes('Motocicletas'));
  let seleccionado;
  M.modalEscanear=async(id,categoria)=>{seleccionado={id,categoria};};
  ctx.document.getElementById=id=>id==='moto-unidad'?{value:'0'}:{checked:false};
  await M.iniciarMoto();
  ok('no conecta sin comprobar compatibilidad',!seleccionado);
  ctx.document.getElementById=id=>id==='moto-unidad'?{value:'0'}:{checked:true};
  await M.iniciarMoto();
  ok('moto usa el escáner real con unidad preseleccionada',seleccionado.id==='m1' && seleccionado.categoria==='moto');
  let registro='';
  M._centroScan={por_modulo:[{ecu:2024,nombre:'<img src=x onerror=alert(1)>'}]};
  M._puedePuntoAPunto=()=>({ok:true});
  M._elmPuntoAPunto=fn=>fn();
  M._udsPedir=async()=>[0x51];
  M._log=t=>{registro=t;};
  await M.resetModulo(2024);
  ok('registro de reinicio escapa nombres y conserva flujo',registro.includes('&lt;img') && !registro.includes('<img'));
  fin();
}
main().catch(e=>{console.error(e);process.exitCode=1;});
